#!/bin/bash

# List of URLs to crawl
URLS=(
'https://javascript.info/intro',
'https://javascript.info/manuals-specifications',
'https://javascript.info/code-editors',
'https://javascript.info/devtools',
'https://javascript.info/first-steps',
'https://javascript.info/hello-world'.
'https://javascript.info/structure',
'https://javascript.info/strict-mode',
'https://javascript.info/variables',
'https://javascript.info/types',
'https://javascript.info/alert-prompt-confirm',
'https://javascript.info/type-conversions',
'https://javascript.info/operators',
'https://javascript.info/comparison',
'https://javascript.info/ifelse',
'https://javascript.info/logical-operators',
'https://javascript.info/nullish-coalescing-operator',
'https://javascript.info/while-for',
'https://javascript.info/switch',
'https://javascript.info/function-basics',
'https://javascript.info/function-expressions',
'https://javascript.info/arrow-functions-basics',
'https://javascript.info/javascript-specials',
'https://javascript.info/code-quality',
'https://javascript.info/debugging-chrome',
'https://javascript.info/coding-style',
'https://javascript.info/comments',
'https://javascript.info/ninja-code',
'https://javascript.info/testing-mocha',
'https://javascript.info/polyfills',
'https://javascript.info/object-basics',
'https://javascript.info/object',
'https://javascript.info/object-copy',
'https://javascript.info/garbage-collection',
'https://javascript.info/object-methods',
'https://javascript.info/constructor-new',
'https://javascript.info/optional-chaining',
'https://javascript.info/symbol',
'https://javascript.info/object-toprimitive',
'https://javascript.info/data-types',
'https://javascript.info/primitives-methods',
'https://javascript.info/number',
'https://javascript.info/string',
'https://javascript.info/array',
'https://javascript.info/array-methods',
'https://javascript.info/iterable',
'https://javascript.info/map-set',
'https://javascript.info/weakmap-weakset',
'https://javascript.info/keys-values-entries',
'https://javascript.info/destructuring-assignment',
'https://javascript.info/date',
'https://javascript.info/json',
'https://javascript.info/advanced-functions',
'https://javascript.info/recursion',
'https://javascript.info/rest-parameters-spread',
'https://javascript.info/closure',
'https://javascript.info/var',
"https://javascript.info/global-object",
'https://javascript.info/function-object',
'https://javascript.info/new-function',
'https://javascript.info/settimeout-setinterval',
'https://javascript.info/call-apply-decorators',
'https://javascript.info/bind',
'https://javascript.info/arrow-functions',
'https://javascript.info/object-properties',
'https://javascript.info/property-descriptors',
'https://javascript.info/property-accessors',
'https://javascript.info/prototypes',
'https://javascript.info/prototype-inheritance',
'https://javascript.info/function-prototype',
'https://javascript.info/native-prototypes',
'https://javascript.info/prototype-methods',
'https://javascript.info/classes',
'https://javascript.info/class',
'https://javascript.info/class-inheritance',
'https://javascript.info/static-properties-methods',
'https://javascript.info/private-protected-properties-methods',
'https://javascript.info/extend-natives',
'https://javascript.info/instanceof',
'https://javascript.info/mixins',
'https://javascript.info/error-handling',
'https://javascript.info/try-catch',
'https://javascript.info/custom-errors',
'https://javascript.info/async',
'https://javascript.info/callbacks',
'https://javascript.info/promise-basics',
"https://javascript.info/promise-chaining",
'https://javascript.info/promise-error-handling',
'https://javascript.info/promise-api',
'https://javascript.info/promisify',
'https://javascript.info/microtask-queue',
'https://javascript.info/async-await',
'https://javascript.info/generators-iterators',
'https://javascript.info/generators',
'https://javascript.info/async-iterators-generators',
'https://javascript.info/modules',
'https://javascript.info/modules-intro',
'https://javascript.info/import-export',
'https://javascript.info/modules-dynamic-imports',
'https://javascript.info/js-misc',
'https://javascript.info/proxy',
'https://javascript.info/eval',
'https://javascript.info/currying-partials',
'https://javascript.info/reference-type',
'https://javascript.info/bigint',
'https://javascript.info/unicode',
'https://javascript.info/weakref-finalizationregistry',
'https://javascript.info/ui',


)


echo "🕷️  Starting bulk crawl of ${#URLS[@]} articles..."

# No cd needed if run from project root
for url in "${URLS[@]}"; do
    echo "----------------------------------------"
    python cli.py crawl-web "$url"
    sleep 2
done

echo "----------------------------------------"
echo "✅ Bulk crawl finished!"
